// LOGIN ACTION TYPES
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
// PRODUCTS
export const PRODUCTS_FETCH_START = "PRODUCTS_FETCH_START";
export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
export const PRODUCTS_FETCH_ERROR = "PRODUCTS_FETCH_ERROR";

export const CART_FETCH_START = "CART_FETCH_START";
export const CART_FETCH_SUCCESS = "CART_FETCH_SUCCESS";
export const CART_FETCH_ERROR = "CART_FETCH_ERROR";

export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";
export const CART_REMOVE_SUCCESS = "CART_REMOVE_SUCCESS";
export const CART_UPDATE_SUCCESS = "CART_UPDATE_SUCCESS";

export const ORDER_CREATE_START = "ORDER_CREATE_START";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_ERROR = "ORDER_CREATE_ERROR";

export const ORDER_FETCH_START = "ORDER_FETCH_START";
export const ORDER_FETCH_SUCCESS = "ORDER_FETCH_SUCCESS";
export const ORDER_FETCH_ERROR = "ORDER_FETCH_ERROR";

export const ORDER_FETCH_BY_ID_START = "ORDER_FETCH_BY_ID_START";
export const ORDER_FETCH_BY_ID_SUCCESS = "ORDER_FETCH_BY_ID_SUCCESS";
export const ORDER_FETCH_BY_ID_ERROR = "ORDER_FETCH_BY_ID_ERROR";